[package]
name = "senpy-api"
version = "0.1.0"
authors = ["Fuwn <contact@fuwn.me>"]
edition = "2018"
#description = ""
readme = "README.md"
homepage = "http://github.com/senpy-club/api"
repository = "http://github.com/senpy-club/api"
license = "GPL-3.0-only"
keywords = ["rust", "anime", "senpy"]
publish = false

[dependencies]
rocket = { version = "0.5.0-dev", git = "https://github.com/SergioBenitez/Rocket.git" }
rocket_contrib = { version = "0.5.0-dev", git = "https://github.com/SergioBenitez/Rocket.git" }
reqwest = { version = "0.11.3", features = ["json"] }
tokio = { version = "1.5.0", features = ["full"] }
serde = "1.0.125"
serde_derive = "1.0.125"
rand = "0.8.3"
dotenv = "0.15.0"
