# ------------
# | Wrappers |
# ------------
[tasks.fmt]
command = "cargo"
args = ["fmt"]
private = true

[tasks.check]
command = "cargo"
args = ["check"]
private = true

[tasks.clippy]
command = "cargo"
args = ["clippy"]
private = true

# -------------
# | Executors |
# -------------
[tasks.checkf]
dependencies = ["fmt", "check"]

[tasks.checkfc]
dependencies = ["fmt", "check", "clippy"]

[tasks.run]
dependencies = ["checkf"]
command = "cargo"
args = ["run"]

[tasks.runw]
dependencies = ["checkf"]
command = "cargo"
args = ["run"]
watch = true

[tasks.docker-build]
command = "nix-build"
args = ["docker.nix"]

[tasks.docker-load]
script_runner = "@shell"
script = '''
docker load < result
'''

[tasks.docker-run]
command = "docker"
args = [
  "run",
  "--name", "senpy_api",
  "-p", "1337:80",
  "senpy-club/api"
]

# Build 'n' load
[tasks.bnl]
dependencies = ["docker-build", "docker-load"]
