name = "senpy-club-api-worker"
main = "build/index.js"
workers_dev = true
compatibility_date = "2022-01-20"

[build]
command = "worker-build --release"

[[rules]]
globs = ["**/*.wasm"]
type = "CompiledWasm"
fallthrough = true
